### ISSUE TITLE
Other plugins can't override ChatEvent

### ISSUE THREAD

**Issue by Cadiducho** [CodeCrafter47/FreeBungeeChat#3]
Because of EventPriority is HIGHEST, other plugins can't use this Event, for example, to admin chat. /a enable this chat an then your write normally.... but nope, you can't
https://github.com/CodeCrafter47/FreeBungeeChat/blob/master/src/main/java/codecrafter47/freebungeechat/FreeBungeeChat.java#L149
Please, fix it to only HIGH or NORMAL

**Comment by CodeCrafter47** [comment]
You don't seem to understand event priorities. HIGHEST means the plugin is the last one to handle the event. Other plugins with lower priorities will receive the event before. If they cancel the event FreeBungeeChat ignores it.
If I remember correctly at the beginning I had the priority at normal, but set it to highest to achieve compatibility with that BungeeChatFilter.
